name: Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
  push:
    branches:
      - main
    paths:
      - 'src/TournamentApp.Api/**'
      - 'src/TournamentApp.Application/**'
      - 'src/TournamentApp.Domain/**'
      - 'src/TournamentApp.Infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Fly.io
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Set Fly.io secrets
      if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        flyctl secrets set \
          ConnectionStrings__DefaultConnection="${{ secrets.DATABASE_CONNECTION_STRING }}" \
          Cognito__UserPoolId="${{ secrets.COGNITO_USER_POOL_ID }}" \
          Cognito__Authority="${{ secrets.COGNITO_AUTHORITY }}" \
          --app ${{ secrets.FLY_APP_NAME }}
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      run: |
        flyctl deploy \
          --app ${{ secrets.FLY_APP_NAME }} \
          --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      working-directory: .

    - name: Health check
      run: |
        sleep 30
        curl -f ${{ secrets.FLY_APP_URL }}/health || exit 1

    - name: Database check
      run: |
        curl -f ${{ secrets.FLY_APP_URL }}/db-check || exit 1

