name: Deploy Web

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
  push:
    branches:
      - main      # Deploys to dev
      - production # Deploys to prod (if you create this branch)
    paths:
      - 'src/TournamentApp.Web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/production' && 'prod' || 'dev') }}
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/TournamentApp.Web/TournamentApp.Web.csproj

    - name: Build Blazor WASM
      run: dotnet publish src/TournamentApp.Web/TournamentApp.Web.csproj -c Release -o publish
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}

    - name: Verify publish output
      run: |
        echo "Publish directory contents:"
        ls -la publish/
        echo "Looking for index.html:"
        find publish -name "index.html" -type f

    - name: Prepare deployment files
      run: |
        # Blazor WASM publishes to wwwroot subfolder, so we need to deploy from there
        if [ -d "publish/wwwroot" ]; then
          echo "Found wwwroot folder, using it for deployment"
          DEPLOY_DIR="publish/wwwroot"
        elif [ -f "publish/index.html" ]; then
          echo "Found index.html at root, using root for deployment"
          DEPLOY_DIR="publish"
        else
          echo "Error: index.html not found in expected locations"
          exit 1
        fi
        
        # Update base href for GitHub Pages subdirectory hosting
        REPO_NAME="${{ github.event.repository.name }}"
        BASE_HREF="/${REPO_NAME}/"
        echo "Setting base href to: ${BASE_HREF}"
        sed -i "s|<base href=\"/\" />|<base href=\"${BASE_HREF}\" />|g" "${DEPLOY_DIR}/index.html"
        
        # Create 404.html for SPA routing
        cp "${DEPLOY_DIR}/index.html" "${DEPLOY_DIR}/404.html"
        
        # Create .nojekyll to disable Jekyll processing (required for Blazor WASM)
        touch "${DEPLOY_DIR}/.nojekyll"
        
        echo "Deployment files prepared in: ${DEPLOY_DIR}"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/wwwroot
        destination_dir: /
        cname: false
        keep_files: false

    - name: Verify deployment
      run: |
        echo "Waiting for GitHub Pages to update..."
        sleep 5
        echo "Check the gh-pages branch to verify files were deployed:"
        echo "https://github.com/${{ github.repository }}/tree/gh-pages"

    - name: Validate homepage
      run: |
        sleep 15
        # Try environment variable first, then secret
        WEB_URL="${{ vars.WEB_APP_URL }}"
        if [ -z "$WEB_URL" ]; then
          WEB_URL="${{ secrets.WEB_APP_URL }}"
        fi
        if [ -z "$WEB_URL" ]; then
          echo "Error: WEB_APP_URL is not set or is empty"
          echo "Please set WEB_APP_URL as an environment variable or secret in the dev environment"
          exit 1
        fi
        echo "Validating URL: $WEB_URL"
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$WEB_URL")
        echo "HTTP Status: $STATUS"
        if [ "$STATUS" -ne 200 ]; then
          echo "Warning: Homepage returned status $STATUS"
          echo "This might be normal if GitHub Pages is still deploying (can take a few minutes)"
          echo "You can manually check: $WEB_URL"
          # Don't fail the workflow - GitHub Pages can take time to propagate
        else
          echo "Homepage is accessible!"
        fi

